const Items = [
    {
      id: 1,
      mainImage: "https://i.ibb.co/DfP4xR0/ac2dd69a-a53f-4a44-b37f-f5bd54c9d66f.jpg",
      // img: [
      //   "https://i.ibb.co/qMCRNkc/76a742700f3.png",
      // ],
      features: [
        "User Type Dashboard",
        "Popular Classes",
        "Popular Instructor",
        "Available Seats",
        "Secure Payment by Stripe",
        "Student Can Msg Their Instructor",
        "Admin Can Approve or Decline Classes",
        "Admin Can Also Delete User Information",
      ],
      technologies: [
        "React",
        "TailwindCSS",
        "daisyui",
        "Nodejs",
        "Express js",
        "Dotenv",
        "React Query",
        "React Hooks",
        "Json Web Token (JWT)",
        "Axios",
        "Framer Motion",
        "react-helmet-async",
        "react-hook-form",
        "react-hot-toast",
        "react-icons",
        "Stripe",
        "sweetalert2",
        "swiper",
        "firebase",
        "MongoDB",
      ],
      title: "The Theater Arts Institute",
      description:
        "The Theater Arts Institute is a cutting-edge full stack React application designed to provide an immersive learning experience for students interested in the world of theater. With a user-friendly interface and seamless functionality, the app allows students to easily browse and purchase a wide range of theater courses.",
      category: "business",
      liveLink: "https://648c62b6aa4e2d1167d6411e--dapper-strudel-63dcfc.netlify.app/",
      clientlink: "https://github.com/Barkatzx/Theater-art-institute-client",
      serverlink: "https://github.com/Barkatzx/Theater-art-institute-server",
    },
    {
      id: 2,
      mainImage: "https://i.ibb.co/jkZwYQq/28917574-c2c0-452d-820b-45970de8288f.jpg",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1682701456/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-1_jppjdj.png",
      // ],
      features: [
        "User registration and login",
        "Authentication using JWT Tokens",
        "Story searching and pagination",
        "CRUD operations (Story create, read, update and delete)",
        "Responsive Design",
        "404 Page and many more.",
      ],
      technologies: [
        "React",
        "React Hooks",
        "React Icons",
        "Axios",
        "CSS",
        "UUID",
        "NodeJS",
        "ExpressJS",
        "MongoDB",
        "Express Asynsc Handler",
        "Json Web Token",
        "Dontenv",
        "Cors",
      ],
      title: "Chef Info",
      description:
        "Chef Info is a comprehensive full stack website dedicated to satisfying your culinary cravings. Whether you're in search of your favorite cuisine or eager to discover a new chef's delightful creations, Chef Info is your ultimate destination. Explore a wide range of delectable dishes and get to know the talented chefs behind them. From mouthwatering recipes to captivating stories of culinary expertise, Chef Info is your gateway to a world of gastronomic delight",
      category: "personal",
      liveLink: "https://chef-master-auth-firebase.web.app/",
      clientlink: "https://github.com/Barkatzx/chef-master-client",
      serverlink: "https://github.com/Barkatzx/chef-master-server",
    },
    {
      id: 3,
      mainImage: "https://i.ibb.co/d5TRQwz/517fac24-da34-4054-9c1e-cae0f0f60607.jpg",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1684312778/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-1_lcun2a.png",
      // ],
      features: [
        "Search Job",
        "Applied Job",
        "Filter Job",
        "Delete Favorites",
        "404 Page and many more",
        "Responsive Design",
      ],
      technologies: [
        "React",
        "React Hooks",
        "React Router Dom",
        "fontawesome",
        "Tailwind",
        "DaisyUi",
        "React icon",
        "React Toastify",
        "recharts",
      ],
      title: "Job Hunt",
      description:
        "Job Hunt is your go-to Front End website for simplifying your job search process. With a user-friendly interface, it allows you to effortlessly apply for jobs and efficiently filter through job listings. Discover your dream career with ease, thanks to Job Hunt's intuitive features that help you connect with the perfect opportunities.",
      category: "personal",
      liveLink: "https://dancing-scone-cede12.netlify.app/",
      clientlink: "https://github.com/Barkatzx/job-hunt",
    },
    {
      id: 4,
      mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-2_vsab0u.png",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-1_gywmlj.png",
      // ],
      features: [
        "Login Admin",
        "Add employee",
        "Edit employee",
        "Remove employee",
        "Add position",
        "Edit position",
        "Remove position",
        "Display data, input attendance, edit attendance and delete employee absences",
        "Employee Salary Deduction Setting",
        "Display data, input salary data, edit salary data and delete employee salary data",
        "Print payroll reports, absences, and payslips",
        "Change admin and employee passwords",
        "Login Employees/Staff",
        "Print employees/staff salary reports from personal accounts",
        "404 Page and many more",
        "Responsive Design",
      ],
      technologies: [
        "React",
        "React Hooks",
        "React Icons",
        "React Vite",
        "Redux",
        "Redux Toolkit",
        "Tailwind CSS",
        "Apexcharts",
        "Localforage",
        "Match Sorter",
        "Axios",
        "Node JS",
        "Express JS",
        "MySQL",
        "Cors",
        "JWT",
        "Bycrypt",
        "Cookie Parser",
        "Dotenv",
        "MySQL 12",
        "Nodemon",
        "Sequelize",
      ],
      title: "Employee Salary Management",
      description:
        "Warehouse website with employee/employee management, add employee and job title options. Employee attendance data setting salary deductions and salary data. Print salary reports, attendance and salary data and many other features.",
      category: "business",
      liveLink: "https://berthutapea.vercel.app/employee-salary-management",
      codeLink: "https://github.com/berthutapea/mern-employee-salary-management",
    },
    {
      id: 5,
      mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
      // ],
      features: [
        "Add Student",
        "Edit Student",
        "Remove Student",
        "No Student Page",
        "Responsive Design",
        "404 Page and many more",
      ],
      technologies: [
        "React",
        "React Hooks",
        "React Router Dom",
        "Axios",
        "Bootstrap",
        "React Icons",
        "Sweet Alert2",
        "Node JS",
        "Express JS",
        "Cors",
        "Mongoose",
        "Dotenv",
        "Nodemon",
        "MongoDB",
      ],
      title: "Student Management System",
      description:
        "Fullstack open source student management system application made with MongoDB, Express, React & Nodejs (MERN)",
      category: "business",
      liveLink: "https://sttiss.vercel.app/",
      codeLink: "https://github.com/berthutapea/mern-student-management-system",
    },
    {
      id: 6,
      mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-2_iwduig.png",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-1_gpiiro.png",
      // ],
      features: [
        "Mobile Responsive",
        "Beautiful Animations",
        "Rapid Controls",
        "High Score",
        "Mario Background Music",
        "Jump & Game Over Sound Effect",
      ],
      technologies: [
        "React",
        "CSS",
        "React Hooks",
        "React Router",
        "React Redux",
      ],
      title: "Mario Jump",
      description:
        "Mario Jump is an endless running game inspired by the famous Google Chrome's T-Rex Dinosaur Game 🦖. The game is built entirely with ReactJS ⚛ and Redux Toolkit 🔧.",
      category: "game",
      liveLink: "https://mariojumpp.vercel.app/",
      codeLink: "https://github.com/berthutapea/mario-jump-game",
    },
    {
      id: 7,
      mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-1_gqero4.png",
      // ],
      features: [
        "User registration and login",
        "Select the type of question and the difficulty level of the question",
        "Juis time is running and after the time is up it stops automatically",
        "The final results of the answers answered will be shown",
        "Incorrect and correct answer results will be displayed",
        "Responsive Design",
      ],
      technologies: [
        "React",
        "React Vite",
        "Tailwind CSS",
        "Firebase Authentication",
        "Framer Motion",
        "React Firebase Hooks",
        "React Icons",
      ],
      title: "Bert Quiz",
      description:
        "Fullstack open source quiz application",
      category: "personal",
      liveLink: "https://bertquiz.vercel.app/",
      codeLink: "https://github.com/berthutapea/react-quiz",
    },
    {
      id: 8,
      mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
      // ],
      features: [
        "Mobile Responsive",
        "Beautiful Animations",
        "Product",
        "Pricing",
        "Testimonial",
        "Contact",
      ],
      technologies: [
        "React",
        "React Vite",
        "Tailwind CSS",
        "Framer Motion",
        "React Icons",
        "React Hooks",
      ],
      title: "Shopify",
      description:
        "Open source landing page shopify application",
      category: "personal",
      liveLink: "https://shopifyy.vercel.app/",
      codeLink: "https://github.com/berthutapea/react-shopify-landing",
    },
  ];
  
  export default Items;
  