const Items = [
    {
      id: 1,
      mainImage: "https://i.ibb.co/DfP4xR0/ac2dd69a-a53f-4a44-b37f-f5bd54c9d66f.jpg",
      // img: [
      //   "https://i.ibb.co/qMCRNkc/76a742700f3.png",
      // ],
      features: [
        "User Type Dashboard",
        "Popular Classes",
        "Popular Instructor",
        "Available Seats",
        "Secure Payment by Stripe",
        "Student Can Msg Their Instructor",
        "Admin Can Approve or Decline Classes",
        "Admin Can Also Delete User Information",
      ],
      technologies: [
        "React",
        "TailwindCSS",
        "daisyui",
        "Nodejs",
        "Express js",
        "Dotenv",
        "React Query",
        "React Hooks",
        "Json Web Token (JWT)",
        "Axios",
        "Framer Motion",
        "react-helmet-async",
        "react-hook-form",
        "react-hot-toast",
        "react-icons",
        "Stripe",
        "sweetalert2",
        "swiper",
        "firebase",
        "MongoDB",
      ],
      title: "The Theater Arts Institute",
      description:
        "The Theater Arts Institute is a cutting-edge full stack React application designed to provide an immersive learning experience for students interested in the world of theater. With a user-friendly interface and seamless functionality, the app allows students to easily browse and purchase a wide range of theater courses.",
      category: "business",
      liveLink: "https://648c62b6aa4e2d1167d6411e--dapper-strudel-63dcfc.netlify.app/",
      clientlink: "https://github.com/Barkatzx/Theater-art-institute-client",
      serverlink: "https://github.com/Barkatzx/Theater-art-institute-server",
    },
    {
      id: 2,
      mainImage: "https://i.ibb.co/jkZwYQq/28917574-c2c0-452d-820b-45970de8288f.jpg",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1682701456/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-1_jppjdj.png",
      // ],
      features: [
        "User registration and login",
        "Authentication using JWT Tokens",
        "Story searching and pagination",
        "CRUD operations (Story create, read, update and delete)",
        "Responsive Design",
        "404 Page and many more.",
      ],
      technologies: [
        "React",
        "React Hooks",
        "React Icons",
        "Axios",
        "CSS",
        "UUID",
        "NodeJS",
        "ExpressJS",
        "MongoDB",
        "Express Asynsc Handler",
        "Json Web Token",
        "Dontenv",
        "Cors",
      ],
      title: "Chef Info",
      description:
        "Chef Info is a comprehensive full stack website dedicated to satisfying your culinary cravings. Whether you're in search of your favorite cuisine or eager to discover a new chef's delightful creations, Chef Info is your ultimate destination. Explore a wide range of delectable dishes and get to know the talented chefs behind them. From mouthwatering recipes to captivating stories of culinary expertise, Chef Info is your gateway to a world of gastronomic delight",
      category: "personal",
      liveLink: "https://chef-master-auth-firebase.web.app/",
      clientlink: "https://github.com/Barkatzx/chef-master-client",
      serverlink: "https://github.com/Barkatzx/chef-master-server",
    },
    {
      id: 3,
      mainImage: "https://i.ibb.co/d5TRQwz/517fac24-da34-4054-9c1e-cae0f0f60607.jpg",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1684312778/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-1_lcun2a.png",
      // ],
      features: [
        "Search Job",
        "Applied Job",
        "Filter Job",
        "Delete Favorites",
        "404 Page and many more",
        "Responsive Design",
      ],
      technologies: [
        "React",
        "React Hooks",
        "React Router Dom",
        "fontawesome",
        "Tailwind",
        "DaisyUi",
        "React icon",
        "React Toastify",
        "recharts",
      ],
      title: "Job Hunt",
      description:
        "Job Hunt is your go-to Front End website for simplifying your job search process. With a user-friendly interface, it allows you to effortlessly apply for jobs and efficiently filter through job listings. Discover your dream career with ease, thanks to Job Hunt's intuitive features that help you connect with the perfect opportunities.",
      category: "personal",
      liveLink: "https://dancing-scone-cede12.netlify.app/",
      clientlink: "https://github.com/Barkatzx/job-hunt",
    },
    {
      id: 4,
      mainImage: "https://i.ibb.co/rQhbgW4/cd2942c8-3aa7-47e0-be72-408f1bd9a8a4.jpg",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-1_gywmlj.png",
      // ],
      features: [
        "Unique Design",
        "404 Page and many more",
        "Responsive Design",
        "Sort By Date",
      ],
      technologies: [
        "Html",
        "Tailwind Css",
        "Raw Javascript",
        "API",
      ],
      title: "AI Universe Hub",
      description:
        "AI Universe Hub is your gateway to the world of artificial intelligence, offering a curated selection of AI website plans and valuable resources. Our website, built using HTML, CSS, and JavaScript, is designed to provide you with comprehensive insights into AI web development. Explore our selection of AI website plans and access RESTful APIs to kickstart your AI-powered projects. Whether you're a developer or an AI enthusiast, AI Universe Hub is your destination for all things artificial intelligence.",
      category: "business",
      liveLink: "https://boisterous-licorice-88d38d.netlify.app/",
      clientlink: "https://github.com/Barkatzx/Ai-Universe",
    },
    {
      id: 5,
      mainImage: "https://i.ibb.co/Sr5hLCk/fa0e6320-ac78-40d4-87f0-e0067a73c690.jpg",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
      // ],
      features: [
        "Stunning Visual Design",
        "Responsive Layout",
        "Project Showcase",
        "Interactive Elements",
        "Contact Information",
        "Skills Highlight",
        "Testimonials",
        "Blog or Articles",
      ],
      technologies: [
        "React",
        "React Hooks",
        "React Router Dom",
        "Tailwind",
        "React Icons",
        "Sweet Alert2",
        "framer-motion",
        "react-lazyload",
        "react-lottie",
        "react-modern-drawer",
        "react-share",
        "react-slick",
        "react-type-animation",
        "slick-carousel",
        "react-share",
      ],
      title: "Web Developer Portfolio",
      description:
        "Discover the artistry of web development through my captivating front-end portfolio website. Immerse yourself in a world of design, interactivity, and innovation as you explore a collection of my web development projects. With a focus on HTML, CSS, and JavaScript, this website showcases the power of user experience and visual storytelling. Dive into the digital realm and witness the magic of front-end development in action",
      category: "business",
      liveLink: "https://ubiquitous-speculoos-975220.netlify.app/",
      clientlink: "https://github.com/Barkatzx/Update-Portfolio",
    },
    {
      id: 6,
      mainImage: "https://i.ibb.co/89QNFNW/8c223445-c96c-43a3-b934-6f7e1bcf612d.jpg",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-1_gpiiro.png",
      // ],
      features: [
        "Mobile Responsive",
        "Bookmark Articles",
        "Reading Time Tracker",
        "Intuitive User Interface",
        "Cross-Browser Compatibility",
        "Content Recommendations",
      ],
      technologies: [
        "React",
        "Tailwind",
        "Resful API",
      ],
      title: "Knowledge Cafe",
      description:
        "Welcome to Knowledge Cafe, your personalized front-end website for optimizing your reading experience. Discover a platform where you can effortlessly bookmark your favorite articles and precisely gauge your reading time. With an intuitive design crafted using HTML, CSS, and JavaScript, Knowledge Cafe offers a streamlined approach to managing your digital content. Unlock the potential of efficient article tracking and time management at your fingertips.",
      category: "game",
      liveLink: "https://dancing-nasturtium-a125a9.netlify.app/",
      clientlink: "https://github.com/Barkatzx/Knowledge-cafe",
    },
    {
      id: 7,
      mainImage: "https://i.ibb.co/ggTtv1g/7fe8b2e8-b5d8-4489-8437-cf7142dd88b0.png",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-1_gqero4.png",
      // ],
      features: [
        "Responsive Design",
        "Performance Optimization",
        "Cross-Browser Compatibility",
      ],
      technologies: [
        "HTML",
        "CSS",
      ],
      title: "Pump Insta",
      description:
        "Pump Insta is a dynamic and visually captivating HTML and CSS website design. It's a vibrant platform that's dedicated to showcasing the latest trends, news, and inspiration in the fitness and wellness industry. With its bold design and modern aesthetics, Pump Insta is your ultimate source for all things fitness-related. Explore engaging articles, inspiring images, and stay updated with the fast-evolving world of health and wellness.",
      category: "personal",
      liveLink: "https://barkatzx.github.io/instagram-follower/",
      clientlink: "https://github.com/Barkatzx/instagram-follower",
    },
    {
      id: 8,
      mainImage: "https://i.ibb.co/vcrC56D/f07c1f5c-2646-4b7b-bbeb-3da0541e7c42.jpg",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
      // ],
      features: [
        "Mobile Responsive",
        "Beautiful Animations",
        "Testimonial",
        "Contact",
      ],
      technologies: [
        "HTML",
        "CSS",
      ],
      title: "Legal Solution",
      description:
        "Open source landing page shopify application",
      category: "personal",
      liveLink: "https://famous-fairy-97372a.netlify.app/",
      clientlink: "https://github.com/Barkatzx/legal-solution",
    },
    {
      id: 9,
      mainImage: "https://i.ibb.co/f43nzqx/e54f7b80-3dbc-4512-87a4-4770408c9eb0.png",
      // img: [
      //   "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
      // ],
      features: [
        "Calculator",
      ],
      technologies: [
        "HTML",
        "CSS",
        "Javascript",
      ],
      title: "Calculator",
      description:
        "Open source calculator application",
      category: "personal",
      liveLink: "https://barkatzx.github.io/my-calculator/",
      clientlink: "https://github.com/Barkatzx/my-calculator",
    },
  ];
  
  export default Items;
  